### ISSUE TITLE
Core dump in openresty docker container

### ISSUE THREAD

**Issue by Alehap** [openresty/luajit2#100]
I've trouble with core dump recently:
`Core was generated by `nginx: worker process is shutting down                                '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  gc_traverse_frames (g=0x7f9fdfbc13e0, th=0x7f9fd7aa2f00) at lj_gc.c:283
283     lj_gc.c: No such file or directory.
[Current thread is 1 (Thread 0x7f9fdfbe1740 (LWP 3301))]`

My version nginx version: openresty/1.15.8.1
Nginx service is still running at well, but it's generate too much core.* file
Can you please help me to resolve this trouble.
Thanks.

**Comment by agentzh** [comment]
Please try the latest version of OpenResty, 1.17.8.2. There've been many important bugfixes in LuaJIT since 1.15.8.1.

**Comment by Alehap** [comment]
Thank you so much, I'll try your suggestion.
