### ISSUE TITLE
Mike Pall fix some issues

### ISSUE THREAD

**Issue by crasyangel** [openresty/luajit2#101]
When merge?

**Comment by crasyangel** [comment]
https://github.com/LuaJIT/LuaJIT/commits/v2.1

**Comment by agentzh** [comment]
Yeah, we're still working on it. There are quite some merge conflicts we need to resolve.

**Comment by crasyangel** [comment]
> Yeah, we're still working on it. There are quite some merge conflicts we need to resolve.

Any plans?

**Comment by msva** [comment]
Moreover, Mike added some new commits about a week ago, so, it's now more things to merge...

Although, there is nothing hard (I mean, in last-week commits)...

I tried to merge all the things, and I gave up only on merging of `lj_str.c` changes (which were about 3 months ago or so). And there is absolutelly different code...

**Comment by agentzh** [comment]
BTW, the latest Mike Pall changes introduced a new regression in FFI which we are still investigating (this bug would lead to incorrect computation results). So we not done here yet...

**Comment by agentzh** [comment]
Never mind, the FFI regression I mentioned above is a false alarm.
