### ISSUE TITLE
ppc64le build broken

### ISSUE THREAD

**Issue by 0rtz** [openresty/luajit2#131]
I get the following error when trying to build on ppc64le:
```==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: Entering directory '/home/luajit2/src'
CC        lj_init.o
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
vm_ppc.dasc:5692: error: .endif without .if:
    |  .endif
vm_ppc.dasc:*: info: fatal error in input file -- no output file generated.
make[1]: *** [Makefile:668: host/buildvm_arch.h] Error 1
make[1]: Leaving directory '/home/luajit2/src'
make: *** [Makefile:113: default] Error 2
```

The last commit that i can build from is 5f1385520140ea2ece997372bf8cc1affe87c3b8 IIUC it was merged in mainline in 63dee93f4e55faf40d8d417a963cbff5ba606b3b and since then build is broken for some reason

**Comment by zhuizhuhaomeng** [comment]
@0xRZ  would you please try this branch `bug_ppc`

**Comment by zhuizhuhaomeng** [comment]
https://github.com/openresty/luajit2/pull/132/files

**Comment by 0rtz** [comment]
@zhuizhuhaomeng Yes, it builds on bug_ppc branch successfully

**Comment by zhuizhuhaomeng** [comment]
@0xRZ  merged
