### ISSUE TITLE
Link issue with lj_vm_IITERN on s390x 

### ISSUE THREAD

**Issue by velemas** [openresty/luajit2#136]
After applying this PR https://github.com/openresty/luajit2/pull/135, i have a link issue on s390x:
```DYNLINK   libluajit.so
lj_dispatch_dyn.o: In function `lj_dispatch_init':
/home/linux1/luajit2/src/lj_dispatch.c:72: undefined reference to `lj_vm_IITERN'
lj_dispatch_dyn.o: In function `lj_dispatch_update':
/home/linux1/luajit2/src/lj_dispatch.c:145: undefined reference to `lj_vm_IITERN'
/usr/bin/ld: libluajit.so: hidden symbol `lj_vm_IITERN' isn't defined
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:739: libluajit.so] Error 1
```
It looks like this commit https://github.com/openresty/luajit2/commit/bb0f24101565d34ea8b70fdec4dd3f3b35a70e7b lacks the changes for s390x made for all other archs concerning vm_IITERN.

**Comment by xiaocang** [comment]
Hi @zhuizhuhaomeng Can you help with this?

**Comment by zhuizhuhaomeng** [comment]
I don't think I can give you more help because I am not so familiar with this part of the code. And I do not have an s390 machine to verify.

**Comment by velemas** [comment]
@zhuizhuhaomeng free community s390x VMs are available, see https://linuxone.cloud.marist.edu/#/login
