### ISSUE TITLE
LuaJIT Compiler - Getting wrong bytecode when JIT is off.

### ISSUE THREAD

**Issue by 0rangeFox** [openresty/luajit2#146]
Hey guys, I would like to know how I can compile to bytecode via C, but I don't want to with JIT. I have tried several ways to disable JIT, but it still seems to be always on.

I have this snippet code to work with Lua C.
```cpp
class Lua {
public:
    Lua(std::string file) : _file(std::move(file)) {
        this->_lua = luaL_newstate();

        if (!this->_lua)
            throw std::exception();

        luaL_openlibs(this->_lua);

        luaJIT_setmode(this->_lua, -1, LUAJIT_MODE_OFF|LUAJIT_MODE_MAX);

        luaL_loadfile(this->_lua, this->_file.c_str());
        
        this->dump();
    }

private:
    lua_State *_lua;
    std::string _file;

    // https://stackoverflow.com/questions/17597816/lua-dump-in-c
    void dump() {
        FILE* fileTest = fopen("test.luac","wb");
        lua_dump(this->_lua, writer, fileTest);
    }

    static int writer(lua_State *L, const void *p, size_t size, void *u) {
        return (fwrite(p, size, 1, (FILE*) u) != 1) && (size != 0);
    }
};
```

And the bytecode result I get is:
![image](https://user-images.githubusercontent.com/38193239/147714533-e213349d-c305-43c6-b99c-afb3ed7ec926.png)

And if I do with the command luac, I get this:
![image](https://user-images.githubusercontent.com/38193239/147714654-6a786604-144f-4f02-980f-c92263d6196c.png)

Maybe this is related to JIT, or not? Please correct me if I am wrong, I want to understand what I am doing wrong to get those results.

**Comment by XmiliaH** [comment]
The generated bytecode from LuaJIT is not compatible with Lua. From https://luajit.org/extensions.html#string_dump
_Foreign bytecode (e.g. from Lua 5.1) is incompatible and cannot be loaded._
To generate bytecode for Lua as luac does one needs to use the PUC Lua library instead of the LuaJIT one.

**Comment by zhuizhuhaomeng** [comment]
we usually use `luajit -bg  x.lua x.ljbc` to convert Lua to bytecode.
I think luajit can not generate bytecode compatible with luac.

**Comment by 0rangeFox** [comment]
> The generated bytecode from LuaJIT is not compatible with Lua. From https://luajit.org/extensions.html#string_dump
> _Foreign bytecode (e.g. from Lua 5.1) is incompatible and cannot be loaded._
> To generate bytecode for Lua as luac does one needs to use the PUC Lua library instead of the LuaJIT one.

Hey guys, as he said, LuaJIT bytecode isn't compatible with Lua and won't compile for Lua. But I'm disabling LuaJIT so it's suppose to use Lua, right? Could you tell me more about PUC Lua Library? Thanks.

**Comment by XmiliaH** [comment]
There are two totally different Lua implementations. LuaJIT and PUC Lua (can be found here https://www.lua.org/versions.html). These are two libraries both implementing Lua and the Lua C API but use different internals. This means that when disabling the JIT in LuaJIT one still uses LuaJIT but with the JIT disabled. Disabling the JIT will not switch to a different library (PUC Lua). To use PUC Lua one would need to link against this different library instead of LuaJIT.
