### ISSUE TITLE
MIPS environment has a bug in version 20220310

### ISSUE THREAD

**Issue by lison0322** [openresty/luajit2#152]
ARCH：mipsel
Hardware:  MT7621
Kernel:  5.10
GCC: 8.4.0
SDK：openwrt master
Problem version:  luajit2-20220310
Normal version: luajit2-20220309

Example:
```
#!/usr/bin/luajit

function ip2int(ip)
	local ipnum=0
	local n=4

	ip:gsub("([0-9]+)", function(i)
		n = n - 1
		ipnum = ipnum + i*(256^n)
	end)

	print(ip, ipnum, (ipnum == 4294967040) and "ok" or "error")
end

for i=0,50 do
	ip2int("255.255.255.0")
end
```

Result:
```
255.255.255.0   4294967040      ok
255.255.255.0   4294967040      ok
255.255.255.0   4294967040      ok
255.255.255.0   4294967040      ok
255.255.255.0   4294967040      ok
255.255.255.0   4278190590      error
255.255.255.0   4278190590      error
255.255.255.0   4278190590      error
255.255.255.0   4278190590      error
255.255.255.0   4278190590      error
255.255.255.0   4278190590      error
255.255.255.0   4278190590      error
255.255.255.0   4278190590      error
255.255.255.0   4278190590      error
255.255.255.0   4278190590      error
255.255.255.0   765     error
255.255.255.0   765     error
255.255.255.0   765     error
255.255.255.0   765     error
```

**Comment by zhuizhuhaomeng** [comment]
@lison0322  please report the bug to upstream luajit   https://github.com/LuaJIT/LuaJIT

**Comment by lison0322** [comment]
> ARCH：mipsel Hardware: MT7621 Kernel: 5.10 GCC: 8.4.0 SDK：openwrt master Problem version: luajit2-20220310 Normal version: luajit2-20220309
> 
> Example:
> 
> ```
> #!/usr/bin/luajit
> 
> function ip2int(ip)
> 	local ipnum=0
> 	local n=4
> 
> 	ip:gsub("([0-9]+)", function(i)
> 		n = n - 1
> 		ipnum = ipnum + i*(256^n)
> 	end)
> 
> 	print(ip, ipnum, (ipnum == 4294967040) and "ok" or "error")
> end
> 
> for i=0,50 do
> 	ip2int("255.255.255.0")
> end
> ```
> 
> Result:
> 
> ```
> 255.255.255.0   4294967040      ok
> 255.255.255.0   4294967040      ok
> 255.255.255.0   4294967040      ok
> 255.255.255.0   4294967040      ok
> 255.255.255.0   4294967040      ok
> 255.255.255.0   4278190590      error
> 255.255.255.0   4278190590      error
> 255.255.255.0   4278190590      error
> 255.255.255.0   4278190590      error
> 255.255.255.0   4278190590      error
> 255.255.255.0   4278190590      error
> 255.255.255.0   4278190590      error
> 255.255.255.0   4278190590      error
> 255.255.255.0   4278190590      error
> 255.255.255.0   4278190590      error
> 255.255.255.0   765     error
> 255.255.255.0   765     error
> 255.255.255.0   765     error
> 255.255.255.0   765     error
> ```
