### ISSUE TITLE
minilua android build

### ISSUE THREAD

**Issue by maximegmd** [openresty/luajit2#156]
Hi,

I am trying to build the project for multiple platforms, everything works fine except for android, minilua includes limits.h that itself includes a header that does not exist in NDK. 

https://stackoverflow.com/questions/52196472/using-ubuntu-header-lib-in-android-ndk

**Comment by fsfod** [comment]
minilua is only needed in the build system because the host system might not have a Lua interpreter installed, the makefile can be set to use a system provided one with the HOST_LUA make variable.

**Comment by maximegmd** [comment]
Thanks, that makes sense!
