### ISSUE TITLE
编译后静态库体积大

### ISSUE THREAD

**Issue by izxyz** [openresty/luajit2#202]
luajit2.1.0-beat3：763kb
openresty-luajit2：6614kb
编译环境ubuntu20.04交叉编译安卓版静态库

脚本
NDK=/home/xyz/android-ndk-r14b
NDKABI=24
NDKVER=$NDK/toolchains/aarch64-linux-android-4.9 #注意匹配实际版本号
NDKP=$NDKVER/prebuilt/linux-x86_64/bin/aarch64-linux-android- #注意匹配实际路径
NDKF="--sysroot $NDK/platforms/android-$NDKABI/arch-arm64"
make HOST_CC="gcc" CROSS=$NDKP TARGET_FLAGS="$NDKF"

**Comment by zhuizhuhaomeng** [comment]
应该是编译带上了调试信息，你需要把调试信息strip掉。
没有调试信息，出现问题调试非常不方便。

**Comment by zhuizhuhaomeng** [comment]
如果实在不想要调试信息，可以把 -g 选项去掉
