### ISSUE TITLE
Shared dictionary cannot retrieve stale data

### ISSUE THREAD

**Issue by fairyqb** [openresty/luajit2#217]
Please see the following file example:
[shm_stale_resty_test.lua.txt](https://github.com/openresty/luajit2/files/14134539/shm_stale_resty_test.lua.txt)

If this line in the code is commented out, stale data cannot be retrieved from the shared dictionary. 

line 12:
dict:set("init_dict", "init", 0)

**Comment by zhuizhuhaomeng** [comment]
@fairyqb 
> If this line in the code is commented out, stale data cannot be retrieved from the shared dictionary.

This is because the expired entry was reclaimed.
You add init_dict with 0 expired time which means it will not expire.
This entry at the LRU end prevents reclaiming expired entries.

**Comment by fairyqb** [comment]
> @fairyqb
> 
> This is because the expired entry was reclaimed. You add init_dict with 0 expired time which means it will not expire. This entry at the LRU end prevents reclaiming expired entries.

This is a different key.

**Comment by fairyqb** [comment]
https://github.com/openresty/lua-nginx-module/issues/2280

**Comment by zhuizhuhaomeng** [comment]
@fairyqb why did you reopen this issue?

**Comment by zhuizhuhaomeng** [comment]
You should move this issue to lua-nginx-module repository.
