### ISSUE TITLE
why not set "XCFLAGS+= -DLUAJIT_ENABLE_GC64" as default

### ISSUE THREAD

**Issue by GhostZCH** [openresty/luajit2#35]
Sometimes I get "Lua VM crashed, reason: not enough memory" error when I use openresty.  Why not to turn on this switch as default?

**Comment by agentzh** [comment]
It is already set by default on x86_64 in OpenResty's master:

https://github.com/openresty/openresty/commit/3f42731e5

Should get included in the next OpenResty release.

**Comment by agentzh** [comment]
You can try the following preview version NOW :)

https://openresty.org/download/openresty-1.15.8.1rc0.tar.gz

Feedback welcome!
