### ISSUE TITLE
Weird test failure for ARM build when running the official test suite

### ISSUE THREAD

**Issue by agentzh** [openresty/luajit2#38]
When running the test file `test/misc/compare.lua` in the test suite below with the ARM hard-float build of LuaJIT,

https://github.com/openresty/luajit2-test-suite

we see the following test failure:

```
/opt/luajit-arm/bin/luajit-2.1.0-beta3: compare.lua:227: -2147483590
stack traceback:
	[C]: in function 'assert'
	compare.lua:227: in main chunk
	[C]: at 0x00014c88
Failed test when running /home/agentzh/git/luajit2-test-suite/arm-luajit compare.lua 1: 256
```

As we can see that the value to be checked by `< 0` is indeed negative. Disabling the JIT compiler of LuaJIT can no longer reproduce this failure. Looks like a bug in the JIT compiler.

The official v2.1 branch of LuaJIT also exhibits this bug, so it was not a regression introduced by us.

**Comment by agentzh** [comment]
Already reported this to the luajit mailing list: https://www.freelists.org/post/luajit/JIT-compiler-bug-on-ARMv7-hf-for-LuaJIT-v21-caught-by-Mikes-test-suite

**Comment by agentzh** [comment]
Confirmed by Qingjun Wei that it is also reproducible on real ARM hardware: https://www.freelists.org/post/luajit/JIT-compiler-bug-on-ARMv7-hf-for-LuaJIT-v21-caught-by-Mikes-test-suite,1

**Comment by siddhesh** [comment]
Fix: https://github.com/siddhesh/LuaJIT/commit/24429cc95657332e3953a21581d3220884da3d75

**Comment by agentzh** [comment]
@siddhesh Awesome, thanks! I'll have a look shortly. Sorry for the delay on our side.

**Comment by agentzh** [comment]
Merged. Thanks!

@siddhesh BTW, are you seeing these test failures on real ARM hardware? Please see https://github.com/openresty/luajit2/issues/59

**Comment by siddhesh** [comment]
I saw this on real hardware as well as with qemu-arm.  I'll try to reproduce #59 with openresty.
