### ISSUE TITLE
CLA for openresty/luajit2

### ISSUE THREAD

**Issue by Nayana-ibm** [openresty/luajit2#49]
Currently, this project doesn't appear to have a contributor licensing agreement—it isn't clear if by submitting code to this project we're giving you a license to use it, or (as is implied by the statement of copyright ownership on the github page) we're giving you the copyright, not even retaining rights to keep using it ourselves. Could you clarify that we're only giving you a license to use the code we submit, not that we're assigning the copyright to you?

**Comment by agentzh** [comment]
@Nayana-ibm Thanks for asking. For this repository, we do require the contributed code to be and always be under the same MIT license of the original LuaJIT code. You can keep the copyright of the contributed code yourself. You certainly have the right to keep using it yourselves. Please let us know if you have any further questions.

We will make it clear in the README file.

**Comment by agentzh** [comment]
Consider it resolved.
