### ISSUE TITLE
Lua 5.2 Compability as Default

### ISSUE THREAD

**Issue by bungle** [openresty/luajit2#5]
Is there some particular reason for not to add:

```
 -DLUAJIT_ENABLE_LUA52COMPAT
```

by default in OpenResty / lua-resty-cli?

**Comment by agentzh** [comment]
@bungle Since it introduces (minor) incompatible behaviours on the Lua land and it would be a bit hard to disable it from the command-line.

**Comment by bungle** [comment]
Yes, that's a pity. Maybe it is just better to follow on what normal LuaJIT has as a default for better compability.

**Comment by agentzh** [comment]
@bungle I understand. Maybe the (upcoming) official OpenResty binary packages (for those mainstream Linux distributions) can have this option turned on in their LuaJIT by default?
