### ISSUE TITLE
Can not install on CentOS 5.11

### ISSUE THREAD

**Issue by hongpaging** [openresty/luajit2#58]
Used https://github.com/openresty/luajit2/archive/v2.1-20190302.tar.gz

* uname -a

```bash
Linux xxx 2.6.18-308.11.1.el5xen #1 SMP Tue Jul 10 09:29:47 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux
```

* message

```bash

==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: Entering directory `/home1/irteam/src/luajit2-2.1-20190302/src'
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.S
ASM       lj_vm.o
CC        lj_gc.o
BUILDVM   lj_ffdef.h
CC        lj_err.o
CC        lj_char.o
BUILDVM   lj_bcdef.h
CC        lj_bc.o
CC        lj_obj.o
CC        lj_buf.o
CC        lj_str.o
CC        lj_tab.o
CC        lj_func.o
CC        lj_udata.o
CC        lj_meta.o
CC        lj_debug.o
CC        lj_state.o
CC        lj_dispatch.o
CC        lj_vmevent.o
CC        lj_vmmath.o
lj_vmmath.c: In function ‘lj_vm_foldfpm’:
lj_vmmath.c:133: warning: implicit declaration of function ‘exp2’
lj_vmmath.c:133: warning: incompatible implicit declaration of built-in function ‘exp2’
lj_vmmath.c:135: warning: implicit declaration of function ‘log2’
lj_vmmath.c:135: warning: incompatible implicit declaration of built-in function ‘log2’
lj_vmmath.c: In function ‘lj_vm_foldfpm’:
lj_vmmath.c:133: warning: implicit declaration of function ‘exp2’
lj_vmmath.c:133: warning: incompatible implicit declaration of built-in function ‘exp2’
lj_vmmath.c:135: warning: implicit declaration of function ‘log2’
lj_vmmath.c:135: warning: incompatible implicit declaration of built-in function ‘log2’
CC        lj_strscan.o
CC        lj_strfmt.o
CC        lj_strfmt_num.o
CC        lj_api.o
CC        lj_profile.o
CC        lj_lex.o
CC        lj_parse.o
CC        lj_bcread.o
CC        lj_bcwrite.o
CC        lj_load.o
CC        lj_ir.o
lj_ir.c:64: error: ‘exp2’ undeclared here (not in a function)
lj_ir.c:64: error: ‘log2’ undeclared here (not in a function)
make[1]: *** [lj_ir.o] 오류 1
make[1]: Leaving directory `/home1/irteam/src/luajit2-2.1-20190302/src'
make: *** [default] 오류 2
```

Help me! Please.

**Comment by hippi777** [comment]
hi there! :) 

just wild guesses, but i'd try 1st "make clean" (you will know if thats unreasonable), try it wothout "-C src" or maybe the math lib cant be found ... but it can be anything, just these came into my mind in the hope of getting a fast solution... maybe u could try the very same sources on a debian based distro or other luajit versions to close out some possibilities, otherwise i dont think that an old host will be an issue as luajit is c99, so i think its not running forward to break any compatibility...

good luck! :)

**Comment by siddhesh** [comment]
gcc on CentOS 5.x IIRC does not default to c99, so you might need to add -std=c99 or -std=gnu99 to XCFLAGS.

**Comment by hongpaging** [comment]
@szbnwer @siddhesh 

Thank everyone very much.

I succeed after added `XCFLAGS+= -std=gnu99` in `luajit2-2.1-20190302/src/Makefile`.

But, it had warning messages.
Is this ok?

```bash

...
lj_snap.c: In function ‘snap_restoredata’:
lj_snap.c:695: warning: dereferencing type-punned pointer will break strict-aliasing rules
lj_snap.c:706: warning: dereferencing type-punned pointer will break strict-aliasing rules
lj_snap.c: In function ‘snap_restoredata’:
lj_snap.c:695: warning: dereferencing type-punned pointer will break strict-aliasing rules
lj_snap.c:706: warning: dereferencing type-punned pointer will break strict-aliasing rules
...

```

**Comment by hippi777** [comment]
i think thats like a missing casting. actually i havent gone so far now that deep in reading the sources of luajit, and (currently) i only use the official 2.0.4. if others on the same branch have the same warning, then probably u can ignore it, but it can even trigger rare bugs or whatever (not as that would be special to warnings actually... :D ) in the one hand u can run the tests (dunno if theres an openresty fork for it, but if not, then ull find them in the official repo of luajit); on the other hand, u can look around where the warnings say so, and try to find mistakes in the source or find a way to trigger that function, and see if it works...

i think its purely beneficial to know more about the internals, once cuz the great knowledge in it, and cuz there are only a few ppl around luajit who have really good understanding about it, and some of them already taking it to their own directions. so whenever the world would burn in flames, its best to be able to rely on urself. :D luajit already having hard times, but hopefully far from being lost in time and space, just as well, i dont think that openresty will become abandonware any time soon... :)

**Comment by hippi777** [comment]
btw whats ur reason to use `make -C src` instead of `make` in the root directory? otherwise u can set variables from command line like `make XCFLAGS= -std=gnu99` (if i write it correctly) so u wont make a legacy installer for urself :) (and dont forget about `make clean` before compiling it again, if you would like to play with it...)

**Comment by agentzh** [comment]
CentOS 5 reached its end of life more than 2 years ago:

https://www.centosblog.com/centos-eol-dates/

We have no reason to support it on our side either.

**Comment by agentzh** [comment]
If one insists, he can still use a newer version of the gcc toolchain on such old systems to build without upgrading glibc.
