### ISSUE TITLE
Should we use your version or LuaJIT-2.1.0-beta1?

### ISSUE THREAD

**Issue by nikolay** [openresty/luajit2#6]
Just asking...

**Comment by agentzh** [comment]
@nikolay The "agentzh-v2.1" branch of this repos provides the bundled version of LuaJIT in the OpenResty bundle. It's up to you to decide whether to use.

**Comment by nikolay** [comment]
@agentzh I switched to using `v2.1-agentzh` branch, but should I know switch to the latest tag (such as `v2.1-20151028`) instead?

**Comment by agentzh** [comment]
@nikolay Yes.

**Comment by nikolay** [comment]
@agentzh Thanks!

**Comment by nikolay** [comment]
@agentzh How about beta2?

**Comment by agentzh** [comment]
@nikolay Haven't tested it.

**Comment by nikolay** [comment]
@agentzh Okay, thanks!
