### ISSUE TITLE
Can I use the standard nginx together with the luajit2.1 you maintain? thanks!

### ISSUE THREAD

**Issue by ygm521** [openresty/luajit2#68]

**Comment by ygm521** [comment]
What should I pay attention to? What features have you modified?

**Comment by agentzh** [comment]
@ygm521 Yes, you can. But the standard nginx core will have unfixed bugs and also be slower in some cases when be used in the OpenResty context. Some times it may have incompatibilities. You are warned.

**Comment by agentzh** [comment]
We always highly recommend the use of OpenResty to avoid hitting pitfalls and wasting time on both the user side and our side.
