### ISSUE TITLE
Sync with upstream?

### ISSUE THREAD

**Issue by msva** [openresty/luajit2#84]
It seems, Mike pulled some PRs, and commited some changes in 2.1 branch (well, actually, in 2.0 too) few weeks ago.
Wouldn't you pull changes here?

**Comment by thibaultcha** [comment]
Sure. Please allow for some time.

**Comment by agentzh** [comment]
Already sync'd in the v2.1-agentzh branch. Sorry for the delay on our side.

**Comment by exjesper** [comment]
Hi @agentzh, I noticed the sync reverted a bunch of other fixes but couldn't find any ticket explaining why they were reverted. Is it documented somewhere?

**Comment by agentzh** [comment]
@exjesper Because those bugs were already fixed in (slightly) different ways in the upstream repo. I had to revert them before the merge to minimize merge conflicts.

**Comment by exjesper** [comment]
OK, make sense. Thanks for the update
