### ISSUE TITLE
Repo status

### ISSUE THREAD

**Issue by stuta** [openresty/luajit2#88]
There's a new version of luajit with many fixes. Is this repo maintained any more?

**Comment by agentzh** [comment]
@stuta This repo is always maintained. We just didn't know there are recent new commits in the upstream repo (I see we are now about 20 commits behind). Just sync'd and rerun all our tests on x86_64, arm, and aarch64 (The arm arch still has 2 known test failures, BTW).

**Comment by stuta** [comment]
Repo is again behind, there are important changes in original. Maybe setup some watcher?

**Comment by agentzh** [comment]
Just sync'd. Thanks for the info.

**Comment by stuta** [comment]
Should there be some automatic system for main repo changes? 

I really like new table functions and other speed optimizations of this repo, is it possible to ask for merging them to the main repo? Is there any chance of getting them merged?
